name: Daily Collect
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      # - name: Tune GitHub-hosted runner network
      #   # https://github.com/actions/runner-images/issues/1187
      #   uses: smorimoto/tune-github-hosted-runner-network@v1
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run node index.ts
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
