name: Daily Collect
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - uses: smorimoto/tune-github-hosted-runner-network@v1
        # https://github.com/actions/runner-images/issues/1187
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run node index.ts
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: public
          external_repository: SukkaLab/speedtest-net-servers-dist
          publish_branch: master
          personal_token: ${{ secrets.GIT_DEPLOY_TOKEN }}
          user_name: ${{ secrets.GIT_DEPLOY_USER }}
          user_email: ${{ secrets.GIT_DEPLOY_EMAIL }}
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=speedtest-net-servers --commit-dirty=true --branch=main
      - run: |
          mkdir -p /tmp/public/
          echo "Last updated at $(date -u)" > /tmp/public/last-run.txt
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/public
          keep_files: true
          force_orphan: true
          publish_branch: dist
